data:
   gustavo:
     dir: /home/kbhutani/mediator-was/data/predixcan/
     files:
       database: DGN-WB_0.5.txt 
   gtex:
     dir: /projects/gtex/data
     files:
       genotypes: GenotypeFiles/midpoint/GTEx_Analysis_20150112_OMNI_2.5M_5M_450Indiv_chr1to22_phased_genot_imput_info04_maf01_HWEp1E6_ConstrVarIDs.vcf.gz
       expression: ExpressionFiles/gtex.portal.normalized/Whole_Blood_Analysis.expr.txt
   references:
     dbsnp: /projects/references/snp142Common.txt.gz
        
