data:
   gustavo:
     dir: /home/kbhutani/mediator-was/data/predixcan/
     files:
       database: DGN-WB_0.5.txt 
   gtex:
     dir: /projects/gtex
   references:
     dbsnp: /projects/references/snp142Common.txt.gz
        
